### ISSUE TITLE
[BUG] Not working on 1.18.1, crash while summoning.

### ISSUE THREAD

**Issue by M4RC0Sx** [brainsynder-Dev/SimplePets#132]
Please drop the link generated from doing `/pet debug` here

**Describe the bug**
Cant spawn pets on 1.18, using latest 1.18 version from Jenkins.

**Steps to reproduce**
1. Just /pet gui and summon any pet.

**Expected behavior**
Pet gets summoned.

**Additional Information**
This server is running Paper version git-Paper-71 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 91f3eda)

`[17:36:49 ERROR]: Entity threw exception at world:7.143104638567981,72.0,29.419409792723123
java.lang.NoSuchMethodError: 'void net.minecraft.world.entity.ai.navigation.NavigationAbstract.o()'
        at simplepets.brainsynder.versions.v1_18_R1.pathfinder.PathfinderWalkToPlayer.d(PathfinderWalkToPlayer.java:130) ~[SimplePets-1.18.jar:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.stop(WrappedGoal.java:47) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:108) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:857) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3251) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:628) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2907) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:396) ~[?:?]
        at simplepets.brainsynder.versions.v1_18_R1.entity.EntityPet.k(EntityPet.java:442) ~[SimplePets-1.18.jar:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-71]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-71]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-71]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by brainsynder-Dev** [comment]
1.18.1 not supported yet will be in a bit have not had a chance to add it yet

**Comment by brainsynder-Dev** [comment]
This was fixed in [Build: 108](https://ci.pluginwiki.us/job/SimplePets_v5/108/)
